# Generated by Django 4.2.11 on 2025-09-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg', '0006_eegfaa_eegbaseline_faa_eegdiff1_faa_eegdiff2_faa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eegbaseline',
            name='faa',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_ALPHA_ASYMMETRY', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='faa',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_ALPHA_ASYMMETRY', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='faa',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_ALPHA_ASYMMETRY', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='faa',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_ALPHA_ASYMMETRY', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='faa',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_ALPHA_ASYMMETRY', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery1',
            name='faa',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_ALPHA_ASYMMETRY', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery2',
            name='faa',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_ALPHA_ASYMMETRY', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation1',
            name='faa',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_ALPHA_ASYMMETRY', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation2',
            name='faa',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_ALPHA_ASYMMETRY', null=True, upload_to=''),
        ),
    ]
