# Generated by Django 4.2.11 on 2026-03-14 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg', '0007_eegbaseline_faa_eegdiff1_faa_eegdiff2_faa_and_more'),
        ('eeg', '0008_eeg_rename_faa_fields'),
    ]

    operations = [
    ]
