# Generated by Django 4.2.11 on 2026-03-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eeg', '0009_merge_20260314_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eegfaa',
            name='baseline',
            field=models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_BASELINE', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegfaa',
            name='recovery1',
            field=models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_RECOVERY1', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegfaa',
            name='recovery2',
            field=models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_RECOVERY2', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegfaa',
            name='stimulation1',
            field=models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_STIMULATION1', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eegfaa',
            name='stimulation2',
            field=models.ImageField(db_column='EEG_FRONTAL_ASYMMETRY_STIMULATION2', upload_to=''),
        ),
    ]
