# Generated by Django 4.2.11 on 2026-03-14 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eeg', '0010_alter_eegfaa_baseline_alter_eegfaa_recovery1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eegfaa',
            old_name='baseline',
            new_name='faa_baseline',
        ),
        migrations.RenameField(
            model_name='eegfaa',
            old_name='recovery1',
            new_name='faa_recovery1',
        ),
        migrations.RenameField(
            model_name='eegfaa',
            old_name='recovery2',
            new_name='faa_recovery2',
        ),
        migrations.RenameField(
            model_name='eegfaa',
            old_name='stimulation1',
            new_name='faa_stimulation1',
        ),
        migrations.RenameField(
            model_name='eegfaa',
            old_name='stimulation2',
            new_name='faa_stimulation2',
        ),
    ]
