# Generated by Django 4.2.11 on 2026-03-25 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eeg', '0011_rename_baseline_eegfaa_faa_baseline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EEGPSDSpectrogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_dt', models.DateTimeField(auto_now_add=True, db_column='INS_DT')),
                ('upt_dt', models.DateTimeField(auto_now=True, db_column='UPD_DT')),
                ('cz', models.ImageField(blank=True, db_column='EEG_PSD_CZ', null=True, upload_to='')),
                ('c3', models.ImageField(blank=True, db_column='EEG_PSD_C3', null=True, upload_to='')),
                ('c4', models.ImageField(blank=True, db_column='EEG_PSD_C4', null=True, upload_to='')),
                ('fp1', models.ImageField(blank=True, db_column='EEG_PSD_FP1', null=True, upload_to='')),
                ('fp2', models.ImageField(blank=True, db_column='EEG_PSD_FP2', null=True, upload_to='')),
                ('f3', models.ImageField(blank=True, db_column='EEG_PSD_F3', null=True, upload_to='')),
                ('f4', models.ImageField(blank=True, db_column='EEG_PSD_F4', null=True, upload_to='')),
                ('f7', models.ImageField(blank=True, db_column='EEG_PSD_F7', null=True, upload_to='')),
                ('f8', models.ImageField(blank=True, db_column='EEG_PSD_F8', null=True, upload_to='')),
                ('t3', models.ImageField(blank=True, db_column='EEG_PSD_T3', null=True, upload_to='')),
                ('t4', models.ImageField(blank=True, db_column='EEG_PSD_T4', null=True, upload_to='')),
                ('p3', models.ImageField(blank=True, db_column='EEG_PSD_P3', null=True, upload_to='')),
                ('p4', models.ImageField(blank=True, db_column='EEG_PSD_P4', null=True, upload_to='')),
            ],
            options={
                'db_table': 'OC_EEG_PSD_SPECTOGRAM',
            },
        ),
        migrations.AddField(
            model_name='eegbaseline',
            name='connectivity2_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegbaseline',
            name='connectivity_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_COH', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegbaseline',
            name='topography_sigma',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity2_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_alpha_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_alpha_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_alpha_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_alpha_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_alpha_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_beta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_beta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_beta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_beta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_beta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_delta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_delta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_delta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_delta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_delta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_gamma_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_gamma_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_gamma_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_gamma_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_gamma_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_COH', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_sigma_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_sigma_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_sigma_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_sigma_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_sigma_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_theta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_theta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_theta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_theta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='connectivity_theta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_alpha_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_alpha_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_alpha_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_alpha_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_alpha_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_beta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_beta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_beta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_beta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_beta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_delta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_delta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_delta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_delta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_delta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_gamma_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_gamma_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_gamma_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_gamma_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_gamma_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_sigma',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_sigma_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_sigma_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_sigma_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_sigma_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_sigma_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_theta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_theta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_theta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_theta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff1',
            name='topography_theta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity2_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_alpha_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_alpha_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_alpha_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_alpha_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_alpha_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_beta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_beta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_beta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_beta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_beta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_delta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_delta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_delta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_delta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_delta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_gamma_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_gamma_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_gamma_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_gamma_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_gamma_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_COH', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_sigma_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_sigma_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_sigma_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_sigma_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_sigma_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_theta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_theta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_theta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_theta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='connectivity_theta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_alpha_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_alpha_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_alpha_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_alpha_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_alpha_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_beta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_beta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_beta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_beta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_beta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_delta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_delta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_delta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_delta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_delta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_gamma_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_gamma_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_gamma_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_gamma_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_gamma_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_sigma',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_sigma_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_sigma_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_sigma_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_sigma_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_sigma_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_theta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_theta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_theta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_theta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff2',
            name='topography_theta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity2_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_alpha_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_alpha_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_alpha_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_alpha_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_alpha_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_beta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_beta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_beta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_beta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_beta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_delta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_delta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_delta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_delta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_delta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_gamma_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_gamma_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_gamma_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_gamma_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_gamma_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_COH', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_sigma_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_sigma_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_sigma_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_sigma_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_sigma_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_theta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_theta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_theta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_theta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='connectivity_theta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_alpha_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_alpha_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_alpha_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_alpha_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_alpha_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_beta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_beta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_beta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_beta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_beta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_delta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_delta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_delta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_delta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_delta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_gamma_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_gamma_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_gamma_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_gamma_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_gamma_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_sigma',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_sigma_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_sigma_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_sigma_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_sigma_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_sigma_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_theta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_theta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_theta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_theta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff3',
            name='topography_theta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity2_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_alpha_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_alpha_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_alpha_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_alpha_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_alpha_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_ALPHA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_beta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_beta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_beta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_beta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_beta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_BETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_delta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_delta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_delta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_delta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_delta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_DELTA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_gamma_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_gamma_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_gamma_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_gamma_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_gamma_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_GAMMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_COH', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_sigma_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_sigma_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_sigma_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_sigma_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_sigma_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_theta_n1',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_theta_n2',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_theta_n3',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_theta_rem',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='connectivity_theta_wake',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_THETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_alpha_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_alpha_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_alpha_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_alpha_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_alpha_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_ALPHA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_beta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_beta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_beta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_beta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_beta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_BETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_delta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_delta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_delta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_delta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_delta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_DELTA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_gamma_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_gamma_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_gamma_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_gamma_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_gamma_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_GAMMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_sigma',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_sigma_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_sigma_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_sigma_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_sigma_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_sigma_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_theta_n1',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N1', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_theta_n2',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N2', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_theta_n3',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_N3', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_theta_rem',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_REM', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegdiff4',
            name='topography_theta_wake',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_THETA_WAKE', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegfrontallimbic',
            name='sigma',
            field=models.ImageField(blank=True, db_column='EEG_FRONTAL_LIMBIC_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery1',
            name='connectivity2_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery1',
            name='connectivity_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_COH', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery1',
            name='topography_sigma',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery2',
            name='connectivity2_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery2',
            name='connectivity_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_COH', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegrecovery2',
            name='topography_sigma',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation1',
            name='connectivity2_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation1',
            name='connectivity_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_COH', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation1',
            name='topography_sigma',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation2',
            name='connectivity2_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_PLV', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation2',
            name='connectivity_sigma',
            field=models.ImageField(blank=True, db_column='EEG_CONNECTIVITY_SIGMA_COH', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eegstimulation2',
            name='topography_sigma',
            field=models.ImageField(blank=True, db_column='EEG_TOPOGRAPHY_SIGMA', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eeg',
            name='psd_spectrogram',
            field=models.ForeignKey(db_column='EEG_PSD_SPECTOGRAM_ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eeg', to='eeg.eegpsdspectrogram'),
        ),
    ]
