"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import environ
import datetime
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
ROOT_DIR = environ.Path(__file__) - 3
APPS_DIR = ROOT_DIR.path('backend')
BASE_DIR = Path(__file__).resolve().parent.parent

# .env 파일 로드
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-43z8bf&khe3lm5mk%bqnu&ak%_ox0c_4+&xwgcmi9w@h5-wp*e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
]

LOCAL_APPS = [
    'experiments',
    'ecg',
    'eeg',
    'survey',
    'report',
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'oneclick',
        'USER': 'brainlab',
        'PASSWORD': 'brainlab619',
        'HOST': '34.64.103.152',    # database ip
        'PORT': '3306',             # database port
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(days=1000),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=1400),
    'SIGNING_KEY': 'SECRET',
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('JWT',),
}


CORS_ORIGIN_WHITELIST = [
    'http://127.0.0.1:8000',
    'http://34.64.50.127:8000'
]
CORS_ORIGIN_ALLOW_ALL = True

CORS_ALLOW_CREDENTIALS = True


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    # str(APPS_DIR.path('static')),
    # str(ROOT_DIR.path('backend', 'build')),
]


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_ROOT1 = os.path.join(BASE_DIR, 'build', 'icons')


# Django 기본 로깅은 'django' 로거만 구성한다. experiments.views 처럼 앱 모듈에서
# 만든 로거는 설정이 없어 루트(WARNING)로 떨어지고, logger.info 가 전부 조용히
# 버려진다. AI 리포트의 계측 로그(토큰 수, 이미지 크기, 소요 시간)가 안 보이던
# 이유다. 해당 앱 로거만 INFO 로 올린다 — 다른 앱 로그는 그대로 둔다.
# AI 리포트 생성 결과를 담아둘 캐시.
#
# 파일 기반을 쓰는 이유: uwsgi 가 processes=5 라 워커가 5개다. Django 기본값인
# LocMemCache 는 프로세스마다 따로 존재해서, A 워커가 저장한 것을 B 워커가 못 읽는다.
# 리포트 생성(3분 이상)과 그 결과를 받아가는 요청은 서로 다른 워커에 배정되므로
# 반드시 프로세스 간에 공유되는 저장소여야 한다.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'cache', 'ai_report'),
        'TIMEOUT': 60 * 60 * 6,      # 6시간
        'OPTIONS': {'MAX_ENTRIES': 500},
    }
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,      # Django 자체 로거를 죽이지 않는다
    'formatters': {
        # 구분자는 ASCII 로 둔다. uwsgi stderr 인코딩이 UTF-8 이 아닌 환경에서
        # 유니코드 대시가 이스케이프되어 로그가 지저분해지는 걸 피한다.
        'simple': {'format': '[%(levelname)s] %(asctime)s %(name)s | %(message)s'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'loggers': {
        'experiments': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,             # 루트로 다시 올라가 중복 출력되지 않게
        },
    },
}
