# Generated by Django 6.0.3 on 2026-08-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecg", "0002_hrv_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="HRVRecovery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("int_dt", models.DateTimeField(auto_now_add=True, db_column="INS_DT")),
                ("upt_dt", models.DateTimeField(auto_now=True, db_column="UPD_DT")),
                (
                    "sdnn",
                    models.FloatField(blank=True, db_column="HRV_SDNN", null=True),
                ),
                (
                    "rmssd",
                    models.FloatField(blank=True, db_column="HRV_RMSSD", null=True),
                ),
                (
                    "sdsd",
                    models.FloatField(blank=True, db_column="HRV_SDSD", null=True),
                ),
                (
                    "nn50",
                    models.FloatField(blank=True, db_column="HRV_NN50", null=True),
                ),
                (
                    "pnn50",
                    models.FloatField(blank=True, db_column="HRV_pNN50", null=True),
                ),
                (
                    "tri_index",
                    models.FloatField(blank=True, db_column="HRV_TRI_Index", null=True),
                ),
                (
                    "vlf_rel_power",
                    models.FloatField(blank=True, db_column="HRV_REL_VLF", null=True),
                ),
                (
                    "lf_rel_power",
                    models.FloatField(blank=True, db_column="HRV_REL_LF", null=True),
                ),
                (
                    "hf_rel_power",
                    models.FloatField(blank=True, db_column="HRV_REF_HF", null=True),
                ),
                (
                    "lh_ratio",
                    models.FloatField(blank=True, db_column="HRV_LH_RATIO", null=True),
                ),
                (
                    "norm_lf",
                    models.FloatField(blank=True, db_column="HRV_NORM_LF", null=True),
                ),
                (
                    "norm_hf",
                    models.FloatField(blank=True, db_column="HRV_NORM_HF", null=True),
                ),
                ("psd", models.JSONField(db_column="HRV_PSD")),
                (
                    "heart_rate",
                    models.ImageField(db_column="HRV_HEAD_RATE", upload_to=""),
                ),
                (
                    "comparison",
                    models.ImageField(db_column="HRV_COMPARISON", upload_to=""),
                ),
            ],
            options={
                "db_table": "OC_HRV_RECOVERY",
            },
        ),
        migrations.CreateModel(
            name="HRVStimulation3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("int_dt", models.DateTimeField(auto_now_add=True, db_column="INS_DT")),
                ("upt_dt", models.DateTimeField(auto_now=True, db_column="UPD_DT")),
                (
                    "sdnn",
                    models.FloatField(blank=True, db_column="HRV_SDNN", null=True),
                ),
                (
                    "rmssd",
                    models.FloatField(blank=True, db_column="HRV_RMSSD", null=True),
                ),
                (
                    "sdsd",
                    models.FloatField(blank=True, db_column="HRV_SDSD", null=True),
                ),
                (
                    "nn50",
                    models.FloatField(blank=True, db_column="HRV_NN50", null=True),
                ),
                (
                    "pnn50",
                    models.FloatField(blank=True, db_column="HRV_pNN50", null=True),
                ),
                (
                    "tri_index",
                    models.FloatField(blank=True, db_column="HRV_TRI_Index", null=True),
                ),
                (
                    "vlf_rel_power",
                    models.FloatField(blank=True, db_column="HRV_REL_VLF", null=True),
                ),
                (
                    "lf_rel_power",
                    models.FloatField(blank=True, db_column="HRV_REL_LF", null=True),
                ),
                (
                    "hf_rel_power",
                    models.FloatField(blank=True, db_column="HRV_REF_HF", null=True),
                ),
                (
                    "lh_ratio",
                    models.FloatField(blank=True, db_column="HRV_LH_RATIO", null=True),
                ),
                (
                    "norm_lf",
                    models.FloatField(blank=True, db_column="HRV_NORM_LF", null=True),
                ),
                (
                    "norm_hf",
                    models.FloatField(blank=True, db_column="HRV_NORM_HF", null=True),
                ),
                ("psd", models.JSONField(db_column="HRV_PSD")),
                (
                    "heart_rate",
                    models.ImageField(db_column="HRV_HEAD_RATE", upload_to=""),
                ),
                (
                    "comparison",
                    models.ImageField(db_column="HRV_COMPARISON", upload_to=""),
                ),
            ],
            options={
                "db_table": "OC_HRV_STIMULATION_3",
            },
        ),
        migrations.CreateModel(
            name="HRVStimulation4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("int_dt", models.DateTimeField(auto_now_add=True, db_column="INS_DT")),
                ("upt_dt", models.DateTimeField(auto_now=True, db_column="UPD_DT")),
                (
                    "sdnn",
                    models.FloatField(blank=True, db_column="HRV_SDNN", null=True),
                ),
                (
                    "rmssd",
                    models.FloatField(blank=True, db_column="HRV_RMSSD", null=True),
                ),
                (
                    "sdsd",
                    models.FloatField(blank=True, db_column="HRV_SDSD", null=True),
                ),
                (
                    "nn50",
                    models.FloatField(blank=True, db_column="HRV_NN50", null=True),
                ),
                (
                    "pnn50",
                    models.FloatField(blank=True, db_column="HRV_pNN50", null=True),
                ),
                (
                    "tri_index",
                    models.FloatField(blank=True, db_column="HRV_TRI_Index", null=True),
                ),
                (
                    "vlf_rel_power",
                    models.FloatField(blank=True, db_column="HRV_REL_VLF", null=True),
                ),
                (
                    "lf_rel_power",
                    models.FloatField(blank=True, db_column="HRV_REL_LF", null=True),
                ),
                (
                    "hf_rel_power",
                    models.FloatField(blank=True, db_column="HRV_REF_HF", null=True),
                ),
                (
                    "lh_ratio",
                    models.FloatField(blank=True, db_column="HRV_LH_RATIO", null=True),
                ),
                (
                    "norm_lf",
                    models.FloatField(blank=True, db_column="HRV_NORM_LF", null=True),
                ),
                (
                    "norm_hf",
                    models.FloatField(blank=True, db_column="HRV_NORM_HF", null=True),
                ),
                ("psd", models.JSONField(db_column="HRV_PSD")),
                (
                    "heart_rate",
                    models.ImageField(db_column="HRV_HEAD_RATE", upload_to=""),
                ),
                (
                    "comparison",
                    models.ImageField(db_column="HRV_COMPARISON", upload_to=""),
                ),
            ],
            options={
                "db_table": "OC_HRV_STIMULATION_4",
            },
        ),
        migrations.AddField(
            model_name="hrv",
            name="recovery",
            field=models.ForeignKey(
                db_column="HRV_RECOVERY_ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hrv",
                to="ecg.hrvrecovery",
            ),
        ),
        migrations.AddField(
            model_name="hrv",
            name="stimulation3",
            field=models.ForeignKey(
                db_column="HRV_STIMULATION_3_ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hrv",
                to="ecg.hrvstimulation3",
            ),
        ),
        migrations.AddField(
            model_name="hrv",
            name="stimulation4",
            field=models.ForeignKey(
                db_column="HRV_STIMULATION_4_ID",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hrv",
                to="ecg.hrvstimulation4",
            ),
        ),
    ]
