# Generated by Django 6.0.3 on 2026-09-14 06:52

import booth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                (
                    "token",
                    models.CharField(
                        default=booth.models.new_token,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "kiosk_token",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("phone", "개인 휴대폰"), ("kiosk", "공용 키오스크")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("consent", models.BooleanField(default=False)),
                ("survey_answers", models.JSONField(blank=True, null=True)),
                ("survey_received_at", models.DateTimeField(blank=True, null=True)),
                ("survey_revision", models.PositiveIntegerField(default=0)),
                ("measurement", models.JSONField(blank=True, null=True)),
                (
                    "measurement_received_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("report", models.JSONField(blank=True, null=True)),
                (
                    "report_status",
                    models.CharField(
                        choices=[
                            ("waiting", "설문·측정 대기"),
                            ("pending", "생성 대기"),
                            ("generating", "생성 중"),
                            ("done", "완료"),
                            ("failed", "실패"),
                            ("no_consent", "동의 없음"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                (
                    "report_error",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("report_started_at", models.DateTimeField(blank=True, null=True)),
                ("report_done_at", models.DateTimeField(blank=True, null=True)),
                ("report_attempts", models.PositiveIntegerField(default=0)),
                ("report_generations", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "부스 체험자",
                "verbose_name_plural": "부스 체험자",
            },
        ),
    ]
